# Generated by Django 4.2.16 on 2024-10-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('badge_abonnement', models.BooleanField(default=False)),
                ('renouvellement_auto', models.BooleanField(default=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Avantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_jours', models.PositiveIntegerField(default=30)),
                ('avantages', models.ManyToManyField(blank=True, related_name='abonnements', to='abonnement.avantage')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(max_length=100)),
                ('statut', models.CharField(default='complété', max_length=20)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnement.abonnement')),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.typeabonnement'),
        ),
    ]
