# Generated by Django 4.2.16 on 2024-10-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_recherche', models.IntegerField(default=1)),
                ('style_jeu_recherche', models.CharField(choices=[('Offensif', 'Offensif'), ('Défensif', 'Défensif'), ('Équilibré', 'Équilibré')], default='Équilibré', max_length=100)),
                ('region_recherche', models.CharField(choices=[('Europe', 'Europe'), ('Amérique du Nord', 'Amérique du Nord'), ('Asie', 'Asie')], default='Europe', max_length=100)),
                ('langue_recherche', models.CharField(choices=[('Français', 'Français'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol')], default='Français', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(default=1)),
                ('style_jeu', models.CharField(choices=[('Offensif', 'Offensif'), ('Défensif', 'Défensif'), ('Équilibré', 'Équilibré')], default='Équilibré', max_length=100)),
                ('region', models.CharField(choices=[('Europe', 'Europe'), ('Amérique du Nord', 'Amérique du Nord'), ('Asie', 'Asie')], default='Europe', max_length=100)),
                ('langue', models.CharField(choices=[('Français', 'Français'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol')], default='Français', max_length=100)),
            ],
        ),
    ]
